apiVersion: v1
kind: Service
metadata:
  name: pacman-service
  namespace: pacman
spec:
  type: NodePort
  selector:
    app: pacman
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31234  # можешь указать конкретный или оставить Kubernetes выбрать сам
